-- Seed data master: area, mesin, equipment
-- Generated dari file Excel Mesin.xlsx

do $$
declare
  v_area_id uuid;
  v_mesin_id uuid;
begin
  insert into public.area (nama) values ('BOILED CANDY (FOX''S) FILLING PACKING AREA') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 1') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INCLINE CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GWOLF MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PACKING CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPPING MACHINE BACKPACK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROLLER CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 1 AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING UNIT 1') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'SINGLE WRAPPER') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 4 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 5 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 6 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 1 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 2 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 3 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 7 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 8 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 9 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 10 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'TWIST WRAPPER') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEVIDER CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST WRAPPER AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INCLINE CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 3') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OULET CONVEYOR 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROLLER CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 3 AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BUCKET ELEVATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER 9') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MULTIHEAD WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLER HEAD 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLER HEAD 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'CAN SEAMER') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR (MODULAR, INDOSA)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD  (YAMATO INDOSA)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER  (PHLOX CAN FILL)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TRANSFER CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INDOSA SEAMER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PACKING CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEAMING MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING & SORTING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 2') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 2 AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXING HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BUCKET ELEVATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER HEAD 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET INCLINE CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER HEAD 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROLLER CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING UNIT 2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 4') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 4 AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'MANUAL BULK') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SORTING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING & WEIGHTING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEALING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING HOPER & SORTING') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('BOILED CANDY (FOX''S) PROCESS AREA') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'REWORK TREATMENT') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK DISOLVING TANK 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK DISOLVING TANK 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILTER PRESS REWORK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILTRATION TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK CRUSHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROTARY FILTER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DICALITE DISOLVING TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'VACUUM TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 1') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOL MIX') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'TIPPING SUGAR') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Tipping Big Bag') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Tipping Small Bag') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Dissolving Tank') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Holding Tank') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Rework Tank') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR ROLLER CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR BIG BAG') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR SMALL BAG') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COASTER BIG BAG') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PRP CHECKING STATION') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 2') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOL MIX') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 3') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOL MIX') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLMIX TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLMIX AGITATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RECERVOAR TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOVEABLE REWORK TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXING UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COFFEE SOLUTION DISOLVING TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COFFEE SOLUTION PREPARATION TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 4') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AUTO FEED UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLASH VESSEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AUTO FEED') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INCORPORATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLAVOR PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COLOR PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COLLECTING CHAMBER') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FLAVOR PREPARATION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MICROWAVE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLAVOUR PREPARATION RACK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EKSTRAK PREPARATION RACK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CLEANING STATION FLAV PREP RACK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MEJA PC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COLOR TROLLY') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'GLUCOSE HANDLING') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RECEIVING GLUCOSE PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GLUCOSE TANK 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GLUCOSE TANK 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GLUCOSE TRANSFER PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('BUILDING') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING GENERAL OFFICE') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Gents Toilet 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Ladies Toilet 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Server Room') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Pantry Room') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Integrity Room') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Main Office Room') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Visitor room') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Gents Toilet 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Ladies Toilet 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TERAS BUILDING') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING CANTEEN') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA MASAK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMPIT CANTEEN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PENYAJIAN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PENCUCIAN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA MAKAN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GUDANG') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CUCI TANGAN LUAR KANTIN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA BELAKANG KANTIN') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING MUSHOLA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA WUDHU') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA DALAM MUSHOLA') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING CLINIC') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RUANG KLINIK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOTHER ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING SECURITY GUARD') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA POS SECURITY') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING LAUNDRY') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WASHING MACHINE 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WASHING MACHINE 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING LOCKER') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOCKER GENTS 1 (R/F)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOCKER GENTS 2 (SPV)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LADIES LOCKER 1 (SPV)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LADIES LOCKER 2 (R/F)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET GENTS LOCKER 1 (R/F)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET GENTS LOCKER 2 (SPV)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET LADIES LOCKER 1 (SPV)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET LADIES LOCKER 2 (R/F)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GUDANG ISS') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING QA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DMAIC ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TASTING ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EXHAUST CHIMNEY') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MICROLAB ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GENERAL LAB ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'KEEPING QUALITY ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OFFICE') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING MICROBIOLOGY') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 10') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AUTOCLAVE') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD DRYMIX') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 11') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMPIT 4') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD EXTRUSION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 12') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMPIT 5') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD TABLET') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area BC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area Press') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area AW') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area Packing') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD BOILED CANDY') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PROSES') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA COOLING TUNNEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA WRAPPING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PACKING') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING ENGINEERING') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 15') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 8') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'UPS POWER 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ENGINEERING OFFICE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WORKSHOP AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INDUSTRIAL SERVICE AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TECHNICAL STORE') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING WAREHOUSE RAW MATERIAL') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ALLERGEN ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RACKING WAREHOUSE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA RAW MATERIAL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AG KITCHEN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ARCHIEVE ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EX BLIBLI ROOM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LU OFFICE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA BONGKAR') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING WAREHOUSE PACKAGING MATERIAL') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 17') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 10') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RACKING WAREHOUSE 2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING WAREHOUSE FINISHED GOODS') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 18') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 11') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RACKING WAREHOUSE 3') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'SINGLE WRAPPER') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 2 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 3 MC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 3') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING GUMMY-LANTAI 2') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL GUMMY - LANTAI 2') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('DRYMIX') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRYMIX LINE 1') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLEXIBLE SCREW') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'METAL DETECTOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILVO FILLER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRIMIX LINE 2') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MSK TIPPING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MILO TIPPING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MSK RECEIVING HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MILO RECEIVING HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MSK HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MILO HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHING HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXER RECEIVING HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PADDLE MIXER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXER HOPPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PRODUCT SCREW') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'METAL DETECTOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLER MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PREMIX PREPARATION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MATERIAL HANDLING') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('EXTRUSION') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING PACKING') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 25') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 26') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 27') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 28') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEALER TAPE 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 29') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 30') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'HOPPER 26') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 31') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 7') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 7') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 32') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 33') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 34') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 35') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 36') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 37') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEALER TAPE 7') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 38') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DIE CUT FILLING 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DIE CUT FILLING 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DIE CUT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW MILNA 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW MILNA 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW MILNA 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW KRIZZI 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW KRIZZI 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW KRIZZI 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW BUCKET ELEVATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN KONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECKWEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PACKING MAIN KONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA PM') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FP AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPPING MACHINE BESTPACK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MEJA SAP') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LT.1') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'K-TRON') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'APV TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INLINE LAB PROCESS') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TUMBLER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CREAM PREPARATION TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONV CRIMPER & SPREADER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLATTENING ROLLER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CRIMPER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CCP MD') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EX PROCESS AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LT.2') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA RAW MATERIAL') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PREMIX PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYMIX MIXER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYMIX BUFFER TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU STATION') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('GUMMY CANDY') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING PACKING AREA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SHRINK MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SPIRAL CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - CONVEYOR TRANSFER PRODUCT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - PSA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - TRANSPARENT POLYBAG MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - CHECK WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - TAPPING MACHINE BESTPACK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - CASE WEIGHER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MEJA PC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOBBY LT. 2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS AREA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - SUGAR SB342:B532TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 3- BUCKET ELEVATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 3 - METAL DETECTOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - SUGAR DISOLVING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - PECTIN PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - GELATIN PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 -  COLOR PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - VITAMIN PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - FLAVOUR PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - EXTRACT PREPARATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - CONTIGRAV GUMMY') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - DEPOSITOR GUMMY') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - COOLING TUNNEL GUMMY') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - DEMOLDING MACHINE GUMMY') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - TUMBLER GUMMY') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - BUCKET ELEVATOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - PSA AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - JELLYSTAR COOKER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - FAS DOSHING STATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - GLUCOSE SYRUP BUFFER TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - PROCESS CLEANING STATION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - AHU AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - SLURRY TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LANTAI 4 - WASHING MOLD MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'DEPOSITING AREA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOLD TURNBACK SECTION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOLD EXCHANGE SECTION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WAITING SECTION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU DEPOSITING SECTION') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'CCP MD LT. 3') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING OVER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING KONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'LOBBY LT. 3') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU STATION LT. 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOBBY GUMMY LT.3') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PSA AREA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CLEANING SECTION') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU STATION LT. 2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FINISHED GOOD PSA') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - MEJA PC') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SPIRAL KONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SORTING MACHINE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - PACKING MANUAL JAR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - BESTPACK PACKING') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA AREA') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA  FG') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('INDUSTRIAL SERVICE') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'COMPRESSED AIR') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COMPRESSOR AIR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COMPRESSOR AIR 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COMPRESSOR AIR 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER IS 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER IS 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 3') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PLN DISTRIBUTION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TRAFO') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'GENSET GENERATION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DAILY FUEL TANK') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FUEL PUMP') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EXHAUST FAN') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GENERATOR POWER 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GENERATOR POWER 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 1') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FREON R22 CHILLER GENERATION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS5') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS6') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS7') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS8') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS9') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'AMMONIA CHILLER GENERATION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BASIN WATER CHILLER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CIRCULATION PUMP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CIRCULATION PUMP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CIRCULATION PUMP 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN EXHAUST 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN EXHAUST 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHAIN HOIST') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN EXHAUST FAN 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'APD EQUIPMENT') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFETY SHOWER') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'COOLING TOWER SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 4') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'REHEAT SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS20') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS21') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 8') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'AIR HANDLING UNIT SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 1 (FOX''S PROCESS)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 2 (EXTRUSION FP)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 3 (EXTRUSION PROC)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 4 (FOX''S F/P)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 5 (POLO PRESS)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 6 (POLO WRAPPING)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 7 (DRYMIX)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN COOLING 1 (BC)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN COOLING 2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BOILERS') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BOILER STEAM WANSON') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BURNER IS 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PIPING 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PIPING 3') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'CONDENSATE RETURN SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS22') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS23') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS24') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 7') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FEED WATER SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 8') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS25') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS26') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS27') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS28') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS29') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 9') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS30') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRINKING WATER TREATMENT') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 10') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS31') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS32') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS33') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 11') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BASIN RESERVOIR WATER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS34') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS35') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS36') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS37') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS38') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS39') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 4') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'HOT WATER SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 12 (HOT WATER PRODUCT)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS40') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS41') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 9') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 13') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS42') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 10') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 11') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'WELL SYSTEM') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 3') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 4') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 5') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'AEROBIC SYSTEM TREATRMENT') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 14') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER IS 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER IS 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCFUSER BUBLE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 15') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS43') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS44') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 16') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 17') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS45') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRAINASE') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS46 (FLOOD FRONT FACT1)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS47 (FLOOD FRONT FACT2)') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS48 (LAGOON)') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'INFLUENT TREATMENT') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS49') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS50') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS51') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 18') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'ANAEROBIC SYSTEM REACTOR') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MUR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS52') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS53') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS54') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BURNER IS 2') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PIPING 4') on conflict (mesin_id, nama) do nothing;
  insert into public.area (nama) values ('PRESS CANDY (POLO)') on conflict (nama) do update set nama = excluded.nama returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'LIQUOR DISSOLVING') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AGITATOR 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK 1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP PROD1') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP PROD2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'SUGAR PREPARATION') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'JET FILTER') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROTARY VALVE') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER SYSTEM') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'PRESSING') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PRESSING 1') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'ROLL WRAPPING 1') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET 1') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'ROLL WRAPPING 2') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET 2') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'ROLL WRAPPING 3') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR') on conflict (mesin_id, nama) do nothing;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET 3') on conflict (mesin_id, nama) do nothing;
  insert into public.mesin (area_id, nama) values (v_area_id, 'SINGLE WRAPPING') on conflict (area_id, nama) do update set nama = excluded.nama returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 16') on conflict (mesin_id, nama) do nothing;
end $$;